In [1]:
import pandas as pd
import numpy as np
#input csv files of all data
total_nut_day_1_df = pd.read_csv("DR1TOT.csv") #, dtype = np.float64) #convert_float = True)
total_nut_day_1_df = total_nut_day_1_df.replace(" ", "-1000")
total_nut_day_2_df = pd.read_csv("DR2TOT.csv")
total_nut_day_2_df = total_nut_day_2_df.replace(" ", "-1000")
ind_food_1_df = pd.read_csv("DR1IFF_I.csv")
ind_food_2_df = pd.read_csv("DR2IFF.csv")
demo_df = pd.read_csv("Demographics.csv")
#A_general_reduced = pd.read_csv ("A-matrix-General.csv")
A_Data= pd.read_csv ("A_based_on_data.csv")
nitrient_bounds_df = pd.read_csv ("Nutrient_bounds.csv")
blood_pressure_df = pd.read_csv ("BPQ.csv")
diabetes_df = pd.read_csv ("DIQ.csv")

total_nut_day_1_df = total_nut_day_1_df.astype(float)
total_nut_day_2_df = total_nut_day_2_df.astype(float)
#ind_food_1_df = ind_food_1_df.astype(float)
#ind_food_2_df = ind_food_2_df.astype(float)
total_nut_day_2_df.SEQN

0       84234.0
1       84677.0
2       86158.0
3       88565.0
4       88696.0
         ...
9539    93698.0
9540    93699.0
9541    93700.0
9542    93701.0
9543    93702.0
Name: SEQN, Length: 9544, dtype: float64

In [2]:
total_nut_day_2_df

,SEQN,WTDRD1,WTDR2D,DR2DRSTZ,DR2EXMER,DRABF,DRDINT,DR2DBIH,DR2DAY,DR2LANG,...,DR2TP204,DR2TP205,DR2TP225,DR2TP226,DR2_300,DR2_320Z,DR2_330Z,DR2BWATZ,DR2TWS,candidate
0,84234.0,11103.749750,8817.597213,1.0,52.0,2.0,2.0,5.0,2.0,1.0,...,0.043,0.004,0.001,0.001,2.0,240.0,240.0,0.0,1.0,1.0
1,84677.0,17426.566280,13838.608200,1.0,58.0,2.0,2.0,17.0,3.0,1.0,...,0.009,0.007,0.002,0.039,2.0,0.0,0.0,0.0,1.0,1.0
2,86158.0,61409.769980,65280.989150,1.0,87.0,2.0,2.0,28.0,6.0,1.0,...,0.024,0.000,0.000,0.000,2.0,2880.0,0.0,2880.0,1.0,1.0
3,88565.0,20729.288020,16476.786450,1.0,39.0,2.0,2.0,25.0,4.0,1.0,...,0.197,0.003,0.013,0.057,2.0,435.0,435.0,0.0,1.0,1.0
4,88696.0,17110.636890,14626.517870,1.0,78.0,2.0,2.0,8.0,3.0,1.0,...,0.214,0.004,0.024,0.052,2.0,435.0,435.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9539,93698.0,22737.520470,32447.735930,1.0,87.0,2.0,2.0,49.0,5.0,1.0,...,0.053,0.008,0.016,0.001,2.0,0.0,0.0,0.0,4.0,NaN
9540,93699.0,7902.965021,6592.769825,1.0,52.0,2.0,2.0,29.0,3.0,1.0,...,0.173,0.024,0.028,0.025,2.0,1107.0,0.0,1107.0,4.0,NaN
9541,93700.0,0.000000,-1000.000000,5.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,...,-1000.000,-1000.000,-1000.000,-1000.000,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,NaN
9542,93701.0,37079.694410,0.000000,5.0,-1000.0,2.0,1.0,-1000.0,-1000.0,-1000.0,...,-1000.000,-1000.000,-1000.000,-1000.000,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,NaN
9543,93702.0,67560.380810,55166.938290,1.0,87.0,2.0,2.0,4.0,3.0,1.0,...,0.035,0.267,0.069,0.544,2.0,900.0,900.0,0.0,1.0,NaN

In [3]:
blood_pressure_df_mod = blood_pressure_df[(blood_pressure_df.BPQ020 == 1) 
#                   & (total_nut_day_1_df.DRQSDT3 == 3) 
                  ]
diabetes_df_mod = diabetes_df[(diabetes_df.DIQ160   == str(1)) 
                   | (diabetes_df.DIQ010  == 1) 
                  ]
blood_pressure_df_mod

,SEQN,BPQ020,BPQ030,BPD035,BPQ040A,BPQ050A,BPQ080,BPQ060,BPQ070,BPQ090D,BPQ100D
2,83734.0,1.0,1.0,55,1,1,1,0,1,1,2
9,83744.0,1.0,1.0,53,1,1,2,2,0,0,0
10,83747.0,1.0,1.0,46,1,2,1,0,1,2,0
15,83754.0,1.0,1.0,66,1,1,1,0,1,1,1
16,83755.0,1.0,2.0,58,1,1,2,1,1,2,0
...,...,...,...,...,...,...,...,...,...,...,...
6308,93671.0,1.0,1.0,35,1,1,1,0,1,2,0
6309,93672.0,1.0,1.0,32,1,1,1,0,2,1,1
6313,93679.0,1.0,1.0,23,1,1,1,0,1,1,1
6317,93685.0,1.0,1.0,51,1,1,1,0,1,1,1
6322,93695.0,1.0,1.0,46,1,1,2,1,1,1,1

In [33]:
df1 = total_nut_day_1_df[total_nut_day_1_df.SEQN.isin(blood_pressure_df_mod.SEQN)]
df1

,SEQN,WTDRD1,WTDR2D,DR1DRSTZ,DR1EXMER,DRABF,DRDINT,DR1DBIH,DR1DAY,DR1LANG,...,DRD370QQ,DRD370R,DRD370RQ,DRD370S,DRD370SQ,DRD370T,DRD370TQ,DRD370U,DRD370UQ,DRD370V
2,83734.0,6529.619788,4928.422423,1.0,14.0,2.0,2.0,6.0,7.0,1.0,...,-1000.0,2.0,-1000.0,2.0,-1000.0,2.0,-1000.0,1.0,1.0,2.0
12,83744.0,39927.461278,42766.592413,1.0,61.0,2.0,2.0,8.0,3.0,1.0,...,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0
15,83747.0,20532.818013,16459.927410,1.0,73.0,2.0,2.0,40.0,6.0,1.0,...,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0
22,83754.0,16510.376474,17771.887260,1.0,61.0,2.0,2.0,12.0,4.0,1.0,...,-1000.0,2.0,-1000.0,2.0,-1000.0,2.0,-1000.0,2.0,-1000.0,2.0
23,83755.0,22208.398382,22397.052263,1.0,49.0,2.0,2.0,30.0,3.0,1.0,...,-1000.0,2.0,-1000.0,1.0,1.0,2.0,-1000.0,2.0,-1000.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9513,93671.0,12883.444342,0.000000,1.0,71.0,2.0,1.0,-1.0,6.0,1.0,...,-1000.0,2.0,-1000.0,2.0,-1000.0,1.0,1.0,2.0,-1000.0,2.0
9514,93672.0,0.000000,-1000.000000,5.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,...,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0
9521,93679.0,0.000000,-1000.000000,5.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,...,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0
9526,93685.0,14214.278602,12254.365376,1.0,49.0,2.0,2.0,33.0,6.0,2.0,...,-1000.0,2.0,-1000.0,2.0,-1000.0,1.0,1.0,2.0,-1000.0,2.0
9536,93695.0,45123.399143,33769.964823,1.0,76.0,2.0,2.0,0.0,1.0,1.0,...,-1000.0,2.0,-1000.0,2.0,-1000.0,2.0,-1000.0,2.0,-1000.0,2.0

In [23]:
df2 = total_nut_day_1_df[total_nut_day_1_df.SEQN.isin(diabetes_df_mod.SEQN)]

In [25]:
df3 = df1.append(df2)

In [26]:
len(pd.unique(df3['SEQN']))

2518

In [31]:
total_nut_day_1_df[total_nut_day_1_df.SEQN.isin(df3['SEQN'])]

,SEQN,WTDRD1,WTDR2D,DR1DRSTZ,DR1EXMER,DRABF,DRDINT,DR1DBIH,DR1DAY,DR1LANG,...,DRD370QQ,DRD370R,DRD370RQ,DRD370S,DRD370SQ,DRD370T,DRD370TQ,DRD370U,DRD370UQ,DRD370V
0,83732.0,92670.699919,69945.934107,1.0,71.0,2.0,2.0,-1.0,1.0,1.0,...,-1000.0,2.0,-1000.0,2.0,-1000.0,2.0,-1000.0,2.0,-1000.0,2.0
2,83734.0,6529.619788,4928.422423,1.0,14.0,2.0,2.0,6.0,7.0,1.0,...,-1000.0,2.0,-1000.0,2.0,-1000.0,2.0,-1000.0,1.0,1.0,2.0
3,83735.0,58191.539622,0.000000,1.0,22.0,2.0,1.0,15.0,6.0,1.0,...,-1000.0,2.0,-1000.0,2.0,-1000.0,2.0,-1000.0,2.0,-1000.0,2.0
12,83744.0,39927.461278,42766.592413,1.0,61.0,2.0,2.0,8.0,3.0,1.0,...,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0
15,83747.0,20532.818013,16459.927410,1.0,73.0,2.0,2.0,40.0,6.0,1.0,...,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9521,93679.0,0.000000,-1000.000000,5.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,...,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0
9523,93682.0,21349.815809,17212.817905,1.0,61.0,2.0,2.0,16.0,6.0,1.0,...,-1000.0,2.0,-1000.0,2.0,-1000.0,1.0,1.0,1.0,1.0,2.0
9526,93685.0,14214.278602,12254.365376,1.0,49.0,2.0,2.0,33.0,6.0,2.0,...,-1000.0,2.0,-1000.0,2.0,-1000.0,1.0,1.0,2.0,-1000.0,2.0
9530,93689.0,18897.993342,20341.935124,1.0,49.0,2.0,2.0,8.0,4.0,1.0,...,-1000.0,2.0,-1000.0,2.0,-1000.0,2.0,-1000.0,1.0,4.0,2.0
9536,93695.0,45123.399143,33769.964823,1.0,76.0,2.0,2.0,0.0,1.0,1.0,...,-1000.0,2.0,-1000.0,2.0,-1000.0,2.0,-1000.0,2.0,-1000.0,2.0

In [5]:
df_temp = blood_pressure_df_mod[blood_pressure_df_mod.SEQN.isin(diabetes_df_mod.SEQN)]
ind_food_1_df_mod = ind_food_1_df[ind_food_1_df.SEQN.isin(df_temp.SEQN)]
ind_food_1_df_mod.DR1IFDCD = np.floor(ind_food_1_df_mod.DR1IFDCD/1000000).astype(int)
ind_food_2_df_mod = ind_food_2_df[ind_food_2_df.SEQN.isin(df_temp.SEQN)]
ind_food_2_df_mod.DR2IFDCD = np.floor(ind_food_2_df_mod.DR2IFDCD/1000000).astype(int)
demo_df_mod = demo_df[demo_df.SEQN.isin(df_temp.SEQN)]
demo_df_mod = demo_df_mod [(demo_df_mod.RIDAGEYR >= 18) & (demo_df_mod.RIDAGEYR <= 75)]

D:\Users\farzi\anaconda3\lib\site-packages\pandas\core\generic.py:5516: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [6]:
total_nut_day_1_df
total_nut_day_1_df_mod = total_nut_day_1_df[total_nut_day_1_df.SEQN.isin(df_temp.SEQN)]
total_nut_day_1_df_mod#[(total_nut_day_1_df.DR1TSODI <= 1700)]

,SEQN,WTDRD1,WTDR2D,DR1DRSTZ,DR1EXMER,DRABF,DRDINT,DR1DBIH,DR1DAY,DR1LANG,...,DRD370QQ,DRD370R,DRD370RQ,DRD370S,DRD370SQ,DRD370T,DRD370TQ,DRD370U,DRD370UQ,DRD370V
2,83734.0,6529.619788,4928.422423,1.0,14.0,2.0,2.0,6.0,7.0,1.0,...,-1000.0,2.0,-1000.0,2.0,-1000.0,2.0,-1000.0,1.0,1.0,2.0
12,83744.0,39927.461278,42766.592413,1.0,61.0,2.0,2.0,8.0,3.0,1.0,...,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0
15,83747.0,20532.818013,16459.927410,1.0,73.0,2.0,2.0,40.0,6.0,1.0,...,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0
22,83754.0,16510.376474,17771.887260,1.0,61.0,2.0,2.0,12.0,4.0,1.0,...,-1000.0,2.0,-1000.0,2.0,-1000.0,2.0,-1000.0,2.0,-1000.0,2.0
23,83755.0,22208.398382,22397.052263,1.0,49.0,2.0,2.0,30.0,3.0,1.0,...,-1000.0,2.0,-1000.0,1.0,1.0,2.0,-1000.0,2.0,-1000.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9495,93652.0,5383.506397,0.000000,1.0,61.0,2.0,1.0,23.0,6.0,1.0,...,-1000.0,2.0,-1000.0,2.0,-1000.0,1.0,1.0,2.0,-1000.0,2.0
9499,93656.0,17406.778978,22470.595175,1.0,14.0,2.0,2.0,6.0,5.0,1.0,...,-1000.0,2.0,-1000.0,2.0,-1000.0,1.0,8.0,2.0,-1000.0,2.0
9510,93668.0,23904.975654,25731.486677,1.0,61.0,2.0,2.0,17.0,3.0,2.0,...,-1000.0,2.0,-1000.0,2.0,-1000.0,1.0,1.0,2.0,-1000.0,2.0
9514,93672.0,0.000000,-1000.000000,5.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,...,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0
9526,93685.0,14214.278602,12254.365376,1.0,49.0,2.0,2.0,33.0,6.0,2.0,...,-1000.0,2.0,-1000.0,2.0,-1000.0,1.0,1.0,2.0,-1000.0,2.0

In [8]:
total_nut_day_2_df
total_nut_day_2_df_mod = total_nut_day_2_df[total_nut_day_2_df.SEQN.isin(df_temp.SEQN)]
#total_nut_day_2_df_mod[(total_nut_day_2_df.DR2TSODI <= 1700)]
total_nut_day_2_df_mod

,SEQN,WTDRD1,WTDR2D,DR2DRSTZ,DR2EXMER,DRABF,DRDINT,DR2DBIH,DR2DAY,DR2LANG,...,DR2TP204,DR2TP205,DR2TP225,DR2TP226,DR2_300,DR2_320Z,DR2_330Z,DR2BWATZ,DR2TWS,candidate
8,89722.0,23503.922210,18664.696500,1.0,39.0,2.0,2.0,4.0,4.0,1.0,...,0.091,0.002,0.009,0.012,2.0,960.0,960.0,0.0,1.0,1.0
12,83734.0,6529.619788,4928.422423,1.0,43.0,2.0,2.0,9.0,3.0,1.0,...,0.151,0.009,0.043,0.001,2.0,720.0,720.0,0.0,1.0,NaN
22,83744.0,39927.461280,42766.592410,1.0,51.0,2.0,2.0,13.0,1.0,1.0,...,0.184,0.003,0.019,0.032,2.0,1134.0,120.0,1014.0,1.0,NaN
25,83747.0,20532.818010,16459.927410,1.0,43.0,2.0,2.0,44.0,3.0,1.0,...,0.273,0.016,0.032,0.022,3.0,507.0,0.0,507.0,1.0,NaN
32,83754.0,16510.376470,17771.887260,1.0,43.0,2.0,2.0,16.0,1.0,1.0,...,0.310,0.003,0.011,0.018,1.0,1080.0,240.0,840.0,4.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9495,93652.0,5383.506397,0.000000,5.0,-1000.0,2.0,1.0,-1000.0,-1000.0,-1000.0,...,-1000.000,-1000.000,-1000.000,-1000.000,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,NaN
9499,93656.0,17406.778980,22470.595180,1.0,52.0,2.0,2.0,11.0,3.0,1.0,...,0.132,0.002,0.010,0.028,3.0,1920.0,1920.0,0.0,1.0,NaN
9510,93668.0,23904.975650,25731.486680,1.0,39.0,2.0,2.0,50.0,1.0,2.0,...,0.001,0.001,0.000,0.000,3.0,253.5,0.0,253.5,4.0,NaN
9514,93672.0,0.000000,-1000.000000,5.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,...,-1000.000,-1000.000,-1000.000,-1000.000,-1000.0,-1000.0,-1000.0,-1000.0,-1000.0,NaN
9526,93685.0,14214.278600,12254.365380,1.0,39.0,2.0,2.0,37.0,3.0,2.0,...,0.133,0.000,0.005,0.038,2.0,720.0,0.0,720.0,1.0,NaN

In [16]:
ind_food_2_df_mod

,SEQN,WTDRD1,WTDR2D,DR2ILINE,DR2DRSTZ,DR2EXMER,DRABF,DRDINT,DR2DBIH,DR2DAY,...,DR2IM181,DR2IM201,DR2IM221,DR2IP182,DR2IP183,DR2IP184,DR2IP204,DR2IP205,DR2IP225,DR2IP226
38,83734,6529.619788,4928.422423,1,1,43,2,2,9,3,...,0,0,0,0,0,0,0,0,0,0
39,83734,6529.619788,4928.422423,2,1,43,2,2,9,3,...,0,0,0,0.005,0,0,0,0,0,0
40,83734,6529.619788,4928.422423,3,1,43,2,2,9,3,...,0.383,0.001,0,0.015,0.001,0,0,0,0,0
41,83734,6529.619788,4928.422423,4,1,43,2,2,9,3,...,10.746,0.11,0.016,4.601,0.567,0,0.065,0.007,0.016,0
42,83734,6529.619788,4928.422423,5,1,43,2,2,9,3,...,8.763,0.021,0,1.394,0.147,0.063,0.037,0,0.016,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100479,93685,14214.278600,12254.365380,13,1,39,2,2,37,3,...,0.098,0,0,0.126,0.003,0,0,0,0,0
100480,93685,14214.278600,12254.365380,14,1,39,2,2,37,3,...,0.004,0,0,0.004,0.004,0,0,0,0,0
100481,93685,14214.278600,12254.365380,15,1,39,2,2,37,3,...,0.001,0,0,0.004,0,0,0,0,0,0
100482,93685,14214.278600,12254.365380,16,1,39,2,2,37,3,...,0.001,0,0,0.003,0.002,0,0,0,0,0
100483,93685,14214.278600,12254.365380,17,1,39,2,2,37,3,...,0,0,0,0,0,0,0,0,0,0

In [10]:
df_temp

,SEQN,BPQ020,BPQ030,BPD035,BPQ040A,BPQ050A,BPQ080,BPQ060,BPQ070,BPQ090D,BPQ100D
2,83734.0,1.0,1.0,55,1,1,1,0,1,1,2
9,83744.0,1.0,1.0,53,1,1,2,2,0,0,0
10,83747.0,1.0,1.0,46,1,2,1,0,1,2,0
15,83754.0,1.0,1.0,66,1,1,1,0,1,1,1
16,83755.0,1.0,2.0,58,1,1,2,1,1,2,0
...,...,...,...,...,...,...,...,...,...,...,...
6295,93652.0,1.0,1.0,60,1,1,1,0,1,1,1
6299,93656.0,1.0,1.0,55,1,1,1,0,1,1,1
6306,93668.0,1.0,2.0,60,1,1,2,9,0,0,0
6309,93672.0,1.0,1.0,32,1,1,1,0,2,1,1
6317,93685.0,1.0,1.0,51,1,1,1,0,1,1,1

In [9]:
demo_df_mod

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDAGEMN,RIDRETH1,RIDRETH3,RIDEXMON,RIDEXAGM,...,DMDHREDU,DMDHRMAR,DMDHSEDU,WTINT2YR,WTMEC2YR,SDMVPSU,SDMVSTRA,INDHHIN2,INDFMIN2,INDFMPIR
12,83744,9,2,1,56,,4,4,1,,...,3,3,,20395.535310,20068.662891,2,126,3,3,1.19
15,83747,9,2,1,46,,3,3,1,,...,5,6,,34513.077877,35673.964272,1,121,3,3,.75
22,83754,9,2,2,67,,2,2,1,,...,5,1,5,10495.865944,10191.914345,1,128,6,6,.89
23,83755,9,2,1,67,,4,4,2,,...,5,2,,14080.095558,13991.639152,1,126,5,5,2.04
25,83757,9,2,2,57,,2,2,1,,...,1,4,,11709.112101,12413.062527,1,120,5,5,.77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9920,93652,9,2,1,72,,2,2,1,,...,2,1,2,10706.035881,10821.302974,1,125,3,3,.83
9924,93656,9,2,2,75,,1,1,1,,...,3,2,,11085.152311,10745.266811,1,127,7,7,3.4
9936,93668,9,2,2,73,,1,1,1,,...,1,2,,12211.034893,14756.626820,1,128,1,1,.35
9940,93672,9,2,2,63,,2,2,2,,...,1,1,,8605.869893,9594.546377,2,119,1,1,.2
9953,93685,9,2,1,53,,1,1,2,,...,2,1,2,22441.858682,22794.734098,1,126,3,3,.49

In [12]:
demo_df_mod_male = demo_df_mod[demo_df_mod.RIAGENDR == 1]
demo_df_mod_male

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDAGEMN,RIDRETH1,RIDRETH3,RIDEXMON,RIDEXAGM,...,DMDHREDU,DMDHRMAR,DMDHSEDU,WTINT2YR,WTMEC2YR,SDMVPSU,SDMVSTRA,INDHHIN2,INDFMIN2,INDFMPIR
12,83744,9,2,1,56,,4,4,1,,...,3,3,,20395.535310,20068.662891,2,126,3,3,1.19
15,83747,9,2,1,46,,3,3,1,,...,5,6,,34513.077877,35673.964272,1,121,3,3,.75
23,83755,9,2,1,67,,4,4,2,,...,5,2,,14080.095558,13991.639152,1,126,5,5,2.04
45,83777,9,2,1,56,,5,6,1,,...,2,1,2,13892.041938,14484.987902,2,133,7,7,1.35
117,83849,9,2,1,71,,2,2,1,,...,4,1,,11138.899257,11258.826795,1,127,6,6,1.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9855,93587,9,2,1,29,,4,4,2,,...,4,1,5,41781.078960,41778.706913,2,123,14,14,3.16
9875,93607,9,2,1,50,,2,2,1,,...,4,4,,22598.007224,25399.223761,1,124,10,10,5
9889,93621,9,2,1,66,,2,2,1,,...,2,4,,7920.854536,7778.892166,1,125,,,
9920,93652,9,2,1,72,,2,2,1,,...,2,1,2,10706.035881,10821.302974,1,125,3,3,.83
9953,93685,9,2,1,53,,1,1,2,,...,2,1,2,22441.858682,22794.734098,1,126,3,3,.49

In [13]:
demo_df_mod_female = demo_df_mod[demo_df_mod.RIAGENDR == 2]
demo_df_mod_female

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDAGEMN,RIDRETH1,RIDRETH3,RIDEXMON,RIDEXAGM,...,DMDHREDU,DMDHRMAR,DMDHSEDU,WTINT2YR,WTMEC2YR,SDMVPSU,SDMVSTRA,INDHHIN2,INDFMIN2,INDFMPIR
22,83754,9,2,2,67,,2,2,1,,...,5,1,5,10495.865944,10191.914345,1,128,6,6,.89
25,83757,9,2,2,57,,2,2,1,,...,1,4,,11709.112101,12413.062527,1,120,5,5,.77
53,83785,9,2,2,60,,2,2,1,,...,,1,5,10495.865944,10191.914345,1,128,15,15,5
80,83812,9,2,2,68,,1,1,1,,...,3,1,5,10255.968393,9985.161752,1,124,15,15,5
192,83924,9,2,2,48,,3,3,2,,...,1,1,3,107794.053857,108055.854056,2,123,7,7,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9882,93614,9,2,2,60,,3,3,1,,...,3,6,,45113.908773,44322.114338,2,127,6,6,1.49
9899,93631,9,2,2,68,,3,3,2,,...,3,1,4,40104.396965,39729.988506,2,126,6,6,2.03
9924,93656,9,2,2,75,,1,1,1,,...,3,2,,11085.152311,10745.266811,1,127,7,7,3.4
9936,93668,9,2,2,73,,1,1,1,,...,1,2,,12211.034893,14756.626820,1,128,1,1,.35
9940,93672,9,2,2,63,,2,2,2,,...,1,1,,8605.869893,9594.546377,2,119,1,1,.2

In [7]:
demo_df_mod [(demo_df_mod.RIDAGEYR >= 51)]

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDAGEMN,RIDRETH1,RIDRETH3,RIDEXMON,RIDEXAGM,...,DMDHREDU,DMDHRMAR,DMDHSEDU,WTINT2YR,WTMEC2YR,SDMVPSU,SDMVSTRA,INDHHIN2,INDFMIN2,INDFMPIR
12,83744,9,2,1,56,,4,4,1,,...,3,3,,20395.535310,20068.662891,2,126,3,3,1.19
22,83754,9,2,2,67,,2,2,1,,...,5,1,5,10495.865944,10191.914345,1,128,6,6,.89
23,83755,9,2,1,67,,4,4,2,,...,5,2,,14080.095558,13991.639152,1,126,5,5,2.04
25,83757,9,2,2,57,,2,2,1,,...,1,4,,11709.112101,12413.062527,1,120,5,5,.77
45,83777,9,2,1,56,,5,6,1,,...,2,1,2,13892.041938,14484.987902,2,133,7,7,1.35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9920,93652,9,2,1,72,,2,2,1,,...,2,1,2,10706.035881,10821.302974,1,125,3,3,.83
9924,93656,9,2,2,75,,1,1,1,,...,3,2,,11085.152311,10745.266811,1,127,7,7,3.4
9936,93668,9,2,2,73,,1,1,1,,...,1,2,,12211.034893,14756.626820,1,128,1,1,.35
9940,93672,9,2,2,63,,2,2,2,,...,1,1,,8605.869893,9594.546377,2,119,1,1,.2
9953,93685,9,2,1,53,,1,1,2,,...,2,1,2,22441.858682,22794.734098,1,126,3,3,.49

In [14]:
demo_df_mod_female [(demo_df_mod_female.RIDAGEYR >= 51)]

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDAGEMN,RIDRETH1,RIDRETH3,RIDEXMON,RIDEXAGM,...,DMDHREDU,DMDHRMAR,DMDHSEDU,WTINT2YR,WTMEC2YR,SDMVPSU,SDMVSTRA,INDHHIN2,INDFMIN2,INDFMPIR
22,83754,9,2,2,67,,2,2,1,,...,5,1,5,10495.865944,10191.914345,1,128,6,6,.89
25,83757,9,2,2,57,,2,2,1,,...,1,4,,11709.112101,12413.062527,1,120,5,5,.77
53,83785,9,2,2,60,,2,2,1,,...,,1,5,10495.865944,10191.914345,1,128,15,15,5
80,83812,9,2,2,68,,1,1,1,,...,3,1,5,10255.968393,9985.161752,1,124,15,15,5
243,83975,9,2,2,65,,2,2,1,,...,5,1,3,10495.865944,10191.914345,1,127,14,14,4.11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9882,93614,9,2,2,60,,3,3,1,,...,3,6,,45113.908773,44322.114338,2,127,6,6,1.49
9899,93631,9,2,2,68,,3,3,2,,...,3,1,4,40104.396965,39729.988506,2,126,6,6,2.03
9924,93656,9,2,2,75,,1,1,1,,...,3,2,,11085.152311,10745.266811,1,127,7,7,3.4
9936,93668,9,2,2,73,,1,1,1,,...,1,2,,12211.034893,14756.626820,1,128,1,1,.35
9940,93672,9,2,2,63,,2,2,2,,...,1,1,,8605.869893,9594.546377,2,119,1,1,.2

# initial age differentiation

In [15]:

demo_df_mod_male = demo_df_mod[demo_df_mod.RIAGENDR == 1]
demo_df_mod_female = demo_df_mod[demo_df_mod.RIAGENDR == 2]
demo_male_1825 = demo_df_mod_male [(demo_df_mod_male.RIDAGEYR >= 18) & (demo_df_mod_male.RIDAGEYR <= 25)]
demo_male_2635 = demo_df_mod_male [(demo_df_mod_male.RIDAGEYR >= 26) & (demo_df_mod_male.RIDAGEYR <= 35)]
demo_male_3645 = demo_df_mod_male [(demo_df_mod_male.RIDAGEYR >= 36) & (demo_df_mod_male.RIDAGEYR <= 45)]
demo_male_4655 = demo_df_mod_male [(demo_df_mod_male.RIDAGEYR >= 46) & (demo_df_mod_male.RIDAGEYR <= 55)]
demo_male_5665 = demo_df_mod_male [(demo_df_mod_male.RIDAGEYR >= 56) & (demo_df_mod_male.RIDAGEYR <= 65)]

demo_female_1825 = demo_df_mod_female [(demo_df_mod_female.RIDAGEYR >= 18) & (demo_df_mod_female.RIDAGEYR <= 25)]
demo_female_2635 = demo_df_mod_female [(demo_df_mod_female.RIDAGEYR >= 26) & (demo_df_mod_female.RIDAGEYR <= 35)]
demo_female_3645 = demo_df_mod_female [(demo_df_mod_female.RIDAGEYR >= 36) & (demo_df_mod_female.RIDAGEYR <= 45)]
demo_female_4655 = demo_df_mod_female [(demo_df_mod_female.RIDAGEYR >= 46) & (demo_df_mod_female.RIDAGEYR <= 55)]
demo_female_5665 = demo_df_mod_female [(demo_df_mod_female.RIDAGEYR >= 56) & (demo_df_mod_female.RIDAGEYR <= 65)]

# DASH age differentiation

In [16]:
demo_df_mod_male = demo_df_mod[demo_df_mod.RIAGENDR == 1]
demo_df_mod_female = demo_df_mod[demo_df_mod.RIAGENDR == 2]
demo_male_1930 = demo_df_mod_male [(demo_df_mod_male.RIDAGEYR >= 19) & (demo_df_mod_male.RIDAGEYR <= 30)]
demo_male_3150 = demo_df_mod_male [(demo_df_mod_male.RIDAGEYR >= 31) & (demo_df_mod_male.RIDAGEYR <= 50)]
demo_male_51plus = demo_df_mod_male [(demo_df_mod_male.RIDAGEYR >= 51) & (demo_df_mod_male.RIDAGEYR <= 80)]

demo_female_1930 = demo_df_mod_female [(demo_df_mod_female.RIDAGEYR >= 19) & (demo_df_mod_female.RIDAGEYR <= 30)]
demo_female_3150 = demo_df_mod_female [(demo_df_mod_female.RIDAGEYR >= 31) & (demo_df_mod_female.RIDAGEYR <= 50)]
demo_female_51plus = demo_df_mod_female [(demo_df_mod_female.RIDAGEYR >= 51) & (demo_df_mod_female.RIDAGEYR <= 80)]

In [17]:
demo_female_51plus

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDAGEMN,RIDRETH1,RIDRETH3,RIDEXMON,RIDEXAGM,...,DMDHREDU,DMDHRMAR,DMDHSEDU,WTINT2YR,WTMEC2YR,SDMVPSU,SDMVSTRA,INDHHIN2,INDFMIN2,INDFMPIR
22,83754,9,2,2,67,,2,2,1,,...,5,1,5,10495.865944,10191.914345,1,128,6,6,.89
25,83757,9,2,2,57,,2,2,1,,...,1,4,,11709.112101,12413.062527,1,120,5,5,.77
53,83785,9,2,2,60,,2,2,1,,...,,1,5,10495.865944,10191.914345,1,128,15,15,5
80,83812,9,2,2,68,,1,1,1,,...,3,1,5,10255.968393,9985.161752,1,124,15,15,5
243,83975,9,2,2,65,,2,2,1,,...,5,1,3,10495.865944,10191.914345,1,127,14,14,4.11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9882,93614,9,2,2,60,,3,3,1,,...,3,6,,45113.908773,44322.114338,2,127,6,6,1.49
9899,93631,9,2,2,68,,3,3,2,,...,3,1,4,40104.396965,39729.988506,2,126,6,6,2.03
9924,93656,9,2,2,75,,1,1,1,,...,3,2,,11085.152311,10745.266811,1,127,7,7,3.4
9936,93668,9,2,2,73,,1,1,1,,...,1,2,,12211.034893,14756.626820,1,128,1,1,.35
9940,93672,9,2,2,63,,2,2,2,,...,1,1,,8605.869893,9594.546377,2,119,1,1,.2

In [18]:
def Sample_Generator(DemoAge):
    zeros = [0.0] * 44
    temp1 = ind_food_1_df_mod[ind_food_1_df_mod.SEQN.isin(DemoAge.SEQN)] 
    temp2 = ind_food_2_df_mod[ind_food_2_df_mod.SEQN.isin(DemoAge.SEQN)] 
    SampleAge = pd.read_csv ("X.csv")
    count = 0
    for ind in temp1.index: 
        if (str (temp1['SEQN'][ind]) + 'Day1') not in SampleAge.columns: SampleAge[str (temp1['SEQN'][ind]) + 'Day1'] = zeros
    for ind in temp1.index: 
        for ind2 in SampleAge.index:
            if temp1['DR1IFDCD'][ind] ==  SampleAge['Food Code'][ind2]:
                SampleAge[str (temp1['SEQN'][ind])+ 'Day1'][ind2] += float (temp1['DR1IGRMS'][ind]) / SampleAge ['Serving (g)'][ind2]
    for ind in temp2.index: 
        if (str (temp2['SEQN'][ind]) + 'Day2') not in SampleAge.columns: SampleAge[str (temp2['SEQN'][ind]) + 'Day2'] = zeros
    for ind in temp2.index: 
        for ind2 in SampleAge.index:
            if temp2['DR2IFDCD'][ind] ==  SampleAge['Food Code'][ind2]:
                SampleAge[str (temp2['SEQN'][ind])+ 'Day2'][ind2] += float (temp2['DR2IGRMS'][ind]) / SampleAge ['Serving (g)'][ind2]
    return SampleAge.round(1)

In [20]:
all_1875 = Sample_Generator(demo_df_mod)
male_1875_df = Sample_Generator(demo_df_mod_male)
female_1875_df = Sample_Generator(demo_df_mod_female)
male_1825_df = Sample_Generator(demo_male_1825)
male_2635_df = Sample_Generator(demo_male_2635)
male_3645_df = Sample_Generator(demo_male_3645)
male_4655_df = Sample_Generator(demo_male_4655)
male_5665_df = Sample_Generator(demo_male_5665)
female_1825_df = Sample_Generator(demo_female_1825)
female_2635_df = Sample_Generator(demo_female_2635)
female_3645_df = Sample_Generator(demo_female_3645)
female_4655_df = Sample_Generator(demo_female_4655)
female_5665_df = Sample_Generator(demo_female_5665)

C:\Users\farzi\anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
C:\Users\farzi\anaconda3\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [14]:
all_1880 = Sample_Generator(demo_df_mod)
male_1880_df = Sample_Generator(demo_df_mod_male)
female_1880_df = Sample_Generator(demo_df_mod_female)
male_1930_df = Sample_Generator(demo_male_1930)
male_3150_df = Sample_Generator(demo_male_3150)
male_51plus_df = Sample_Generator(demo_male_51plus)

female_1930_df = Sample_Generator(demo_female_1930)
female_3150_df = Sample_Generator(demo_female_3150)
female_51plus_df = Sample_Generator(demo_female_51plus)

C:\Users\farzi\anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
C:\Users\farzi\anaconda3\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
all_1875.to_csv((r'C:\Users\farzi\OneDrive - Johns Hopkins\Research\Inverse Optimization\Data\Python-codes\Blood Pressure and PreDiabetic Samples\all_1875_df.csv'))
male_1875_df.to_csv((r'C:\Users\farzi\OneDrive - Johns Hopkins\Research\Inverse Optimization\Data\Python-codes\Blood Pressure and PreDiabetic Samples\male_1875_df.csv'))
male_1825_df.to_csv((r'C:\Users\farzi\OneDrive - Johns Hopkins\Research\Inverse Optimization\Data\Python-codes\Blood Pressure and PreDiabetic Samples\male_1825_df.csv'))
male_1825_df.to_csv((r'C:\Users\farzi\OneDrive - Johns Hopkins\Research\Inverse Optimization\Data\Python-codes\Blood Pressure and PreDiabetic Samples\male_1825_df.csv'))
male_2635_df.to_csv((r'C:\Users\farzi\OneDrive - Johns Hopkins\Research\Inverse Optimization\Data\Python-codes\Blood Pressure and PreDiabetic Samples\male_2635_df.csv'))
male_3645_df.to_csv((r'C:\Users\farzi\OneDrive - Johns Hopkins\Research\Inverse Optimization\Data\Python-codes\Blood Pressure and PreDiabetic Samples\male_3645_df.csv'))
male_4655_df.to_csv((r'C:\Users\farzi\OneDrive - Johns Hopkins\Research\Inverse Optimization\Data\Python-codes\Blood Pressure and PreDiabetic Samples\male_4655_df.csv'))
male_5665_df.to_csv((r'C:\Users\farzi\OneDrive - Johns Hopkins\Research\Inverse Optimization\Data\Python-codes\Blood Pressure and PreDiabetic Samples\male_5665_df.csv'))
female_1875_df.to_csv((r'C:\Users\farzi\OneDrive - Johns Hopkins\Research\Inverse Optimization\Data\Python-codes\Blood Pressure and PreDiabetic Samples\female_1875_df.csv'))
female_1825_df.to_csv((r'C:\Users\farzi\OneDrive - Johns Hopkins\Research\Inverse Optimization\Data\Python-codes\Blood Pressure and PreDiabetic Samples\female_1825_df.csv'))
female_2635_df.to_csv((r'C:\Users\farzi\OneDrive - Johns Hopkins\Research\Inverse Optimization\Data\Python-codes\Blood Pressure and PreDiabetic Samples\female_2635_df.csv'))
female_3645_df.to_csv((r'C:\Users\farzi\OneDrive - Johns Hopkins\Research\Inverse Optimization\Data\Python-codes\Blood Pressure and PreDiabetic Samples\female_3645_df.csv'))
female_4655_df.to_csv((r'C:\Users\farzi\OneDrive - Johns Hopkins\Research\Inverse Optimization\Data\Python-codes\Blood Pressure and PreDiabetic Samples\female_4655_df.csv'))
female_5665_df.to_csv((r'C:\Users\farzi\OneDrive - Johns Hopkins\Research\Inverse Optimization\Data\Python-codes\Blood Pressure and PreDiabetic Samples\female_5665_df.csv'))

In [17]:
all_1880.to_csv((r'C:\Users\farzi\OneDrive - Johns Hopkins\Research\Inverse Optimization\Data\Python-codes\Blood Pressure and PreDiabetic Samples\Sample based on DASH age Groups\all_1880_df.csv'))
male_1930_df.to_csv((r'C:\Users\farzi\OneDrive - Johns Hopkins\Research\Inverse Optimization\Data\Python-codes\Blood Pressure and PreDiabetic Samples\Sample based on DASH age Groups\male_1930_df.csv'))
male_3150_df.to_csv((r'C:\Users\farzi\OneDrive - Johns Hopkins\Research\Inverse Optimization\Data\Python-codes\Blood Pressure and PreDiabetic Samples\Sample based on DASH age Groups\male_3150_df.csv'))
male_51plus_df.to_csv((r'C:\Users\farzi\OneDrive - Johns Hopkins\Research\Inverse Optimization\Data\Python-codes\Blood Pressure and PreDiabetic Samples\Sample based on DASH age Groups\male_51plus_df.csv'))
female_1930_df.to_csv((r'C:\Users\farzi\OneDrive - Johns Hopkins\Research\Inverse Optimization\Data\Python-codes\Blood Pressure and PreDiabetic Samples\Sample based on DASH age Groups\female_1930_df.csv'))
female_3150_df.to_csv((r'C:\Users\farzi\OneDrive - Johns Hopkins\Research\Inverse Optimization\Data\Python-codes\Blood Pressure and PreDiabetic Samples\Sample based on DASH age Groups\female_3150_df.csv'))
female_51plus_df.to_csv((r'C:\Users\farzi\OneDrive - Johns Hopkins\Research\Inverse Optimization\Data\Python-codes\Blood Pressure and PreDiabetic Samples\Sample based on DASH age Groups\female_51plus_df.csv'))

In [38]:
tempdf = female_3150_df
tempdf

,Food Code,Name,Serving (g),83924Day1,83963Day1,84006Day1,84285Day1,84383Day1,84493Day1,84765Day1,...,89813Day2,89927Day2,89981Day2,90282Day2,91627Day2,91821Day2,92307Day2,92748Day2,92812Day2,93483Day2
0,11,milk,244.0,0.0,0.0,0.4,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.2,0.0,0.0,0.2,0.0,0.0,1.8
1,12,Cream,32.0,0.0,0.0,0.0,0.9,0.0,0.0,0.0,...,0.9,0.9,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,13,Ice Cream,130.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.1,0.0,0.0,0.0,0.0
3,14,Cheese,32.0,0.0,1.9,0.0,0.2,0.0,0.0,0.0,...,0.0,0.9,0.0,0.0,0.0,0.0,1.2,0.0,0.0,0.0
4,21,Beef,65.0,0.0,0.0,0.0,2.1,0.0,0.0,0.4,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,22,Pork,84.0,0.0,0.0,0.0,0.0,0.8,0.0,0.4,...,0.0,0.0,0.0,0.0,0.2,0.0,1.5,2.0,0.0,0.0
6,23,Lamb/Goat/Veal/Venison,85.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,24,Chicken/Turkey,110.0,0.0,0.0,0.0,2.0,1.2,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.6,0.0,0.0,0.6,1.2
8,25,Sussages,100.0,0.0,0.0,0.0,0.0,0.0,1.5,0.0,...,0.0,0.0,0.0,0.1,0.0,0.0,0.8,0.0,0.0,0.0
9,26,Fish,85.0,0.0,0.0,0.5,0.0,0.0,1.0,0.0,...,0.0,0.0,2.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,27,Stew (meat/rice/vegetable),140.0,0.0,0.0,0.0,0.0,0.0,3.6,0.0,...,0.0,0.0,0.0,0.0,3.3,0.0,0.0,2.4,0.0,0.0
11,28,frozen meal (containing meat and vegetables),312.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.4,0.8,0.0,0.0,0.0
12,31,egg,50.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,32,egg omelet,61.0,0.0,2.2,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.8,2.5,0.0,0.0,0.0,2.0,0.0
14,33,egg omelet substitute,61.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,41,Beans,28.4,0.0,0.0,0.0,0.0,3.4,0.0,0.0,...,0.0,0.0,0.0,4.8,0.0,0.6,0.0,0.0,0.0,0.0
16,42,Nuts,28.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.3,0.0,0.0,0.0
17,43,Seeds,30.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,51,Bread,25.0,2.0,0.0,0.4,4.2,4.2,5.8,0.0,...,2.1,1.8,0.0,2.6,1.1,0.0,3.2,0.0,0.0,0.8
19,52,Biscuits,49.0,0.0,0.6,0.0,0.0,0.0,1.1,0.0,...,0.0,0.0,0.0,1.1,1.2,0.0,0.0,0.0,0.0,0.0
20,53,Cakes/cookies/pies,28.4,0.0,0.0,0.0,1.3,0.0,2.0,4.0,...,4.3,0.0,0.0,0.0,0.0,0.2,1.0,0.0,2.6,8.5
21,54,Crackers,30.0,0.0,0.9,0.7,0.0,0.0,3.2,0.0,...,0.0,0.0,0.0,0.0,0.0,0.1,0.9,0.0,1.3,0.0
22,55,Pancakes/waffles,140.0,0.0,0.9,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.1,0.0,0.0,0.0,0.0
23,56,Macaroni/Noodle/pasta/rice,176.0,0.0,3.0,0.0,0.0,1.2,0.0,0.9,...,0.0,0.0,2.2,0.0,0.0,2.4,0.0,0.0,0.0,0.0
24,57,Cereal,55.0,0.0,0.0,0.5,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5
25,58,Burrito/Taco/Enchilada/Pizza/lasanga,198.0,1.3,2.4,1.9,0.0,0.0,0.0,0.0,...,0.0,2.1,0.0,0.6,0.0,0.0,0.0,0.4,1.9,0.9
26,59,"Meat substitute, cereal- and vegetable protein...",100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,61,grapefruit/lemon/orange,236.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.5,1.1,0.1,0.3,0.0,0.0,0.0,0.7
28,62,dried fruit,28.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,63,raw apple/apricot/avocado/banana/cantaloupe/ch...,182.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,64,fruit juice,249.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31,71,potato,369.0,0.0,0.0,0.0,0.0,0.0,0.1,0.2,...,0.7,0.1,0.0,0.0,0.1,0.0,0.0,0.9,0.0,0.0
32,72,beet greens/collards/cress/romaine/greens/spinach,38.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.8,0.0,0.0,1.8
33,73,carrots/pumpkin/squash/sweet potato/,72.0,3.5,0.0,0.0,0.0,0.0,0.0,0.4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4
34,74,tomato/salsa/,123.0,0.0,0.0,0.0,1.0,0.0,0.2,0.4,...,0.1,0.0,0.1,0.0,0.0,0.0,0.7,0.0,1.1,1.6
35,75,raw vegetables,120.0,0.0,0.0,0.3,1.5,0.0,0.5,0.2,...,0.7,0.3,2.0,0.1,0.0,1.3,1.0,0.0,0.0,0.6
36,77,puerto rican style food,250.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37,78,fruit and vegetable smoothie,233.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.7,0.0,0.0,0.0
38,81,butter,14.2,0.2,0.0,0.0,0.0,1.0,3.6,0.0,...,0.0,0.3,0.0,0.0,0.7,0.0,0.0,0.0,0.0,0.0
39,82,oil,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40,83,salad dressing,14.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.2,0.0,0.0,5.2,0.0,0.0,2.1
41,91,sugar/desserts,200.0,0.2,0.0,0.2,0.0,0.0,0.1,0.0,...,0.5,0.0,0.3,0.0,0.1,0.0,0.0,0.0,0.0,0.0
42,92,coffee/soda drink/iced tea,240.0,3.1,3.7,2.6,5.9,0.0,6.0,0.3,...,3.5,2.6,3.6,1.5,6.8,2.7,3.8,0.6,1.4,1.9
43,95,shakes/drink mixes,166.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Optional: Group Select Foods

In [50]:
#tempdf[(tempdf['Food Code'] == 31)] = 


tempdf = (tempdf.reset_index()        
 .replace({'index': {13:12}})        
 .groupby('index', sort=False).sum() )
tempdf = (tempdf.reset_index()        
 .replace({'index': {14:12}})        
 .groupby('index', sort=False).sum() )
tempdf['Food Code'][12] = 31
tempdf['Serving (g)'][12] = 55
tempdf

C:\Users\farzi\anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\farzi\anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()

,Food Code,Serving (g),83924Day1,83963Day1,84006Day1,84285Day1,84383Day1,84493Day1,84765Day1,84904Day1,...,89813Day2,89927Day2,89981Day2,90282Day2,91627Day2,91821Day2,92307Day2,92748Day2,92812Day2,93483Day2
index,,,,,,,,,,,,,,,,,,,,,
0,11,244.0,0.0,0.0,0.4,0.0,0.0,0.0,0.0,1.8,...,0.0,0.0,0.0,1.2,0.0,0.0,0.2,0.0,0.0,1.8
1,12,32.0,0.0,0.0,0.0,0.9,0.0,0.0,0.0,0.0,...,0.9,0.9,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,13,130.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.1,0.0,0.0,0.0,0.0
3,14,32.0,0.0,1.9,0.0,0.2,0.0,0.0,0.0,0.0,...,0.0,0.9,0.0,0.0,0.0,0.0,1.2,0.0,0.0,0.0
4,21,65.0,0.0,0.0,0.0,2.1,0.0,0.0,0.4,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,22,84.0,0.0,0.0,0.0,0.0,0.8,0.0,0.4,0.0,...,0.0,0.0,0.0,0.0,0.2,0.0,1.5,2.0,0.0,0.0
6,23,85.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,24,110.0,0.0,0.0,0.0,2.0,1.2,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.6,0.0,0.0,0.6,1.2
8,25,100.0,0.0,0.0,0.0,0.0,0.0,1.5,0.0,0.0,...,0.0,0.0,0.0,0.1,0.0,0.0,0.8,0.0,0.0,0.0
9,26,85.0,0.0,0.0,0.5,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,2.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,27,140.0,0.0,0.0,0.0,0.0,0.0,3.6,0.0,0.0,...,0.0,0.0,0.0,0.0,3.3,0.0,0.0,2.4,0.0,0.0
11,28,312.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.4,0.8,0.0,0.0,0.0
12,31,55.0,0.0,2.2,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.9,0.0,1.8,2.5,0.0,0.0,0.0,2.0,0.0
15,41,28.4,0.0,0.0,0.0,0.0,3.4,0.0,0.0,0.0,...,0.0,0.0,0.0,4.8,0.0,0.6,0.0,0.0,0.0,0.0
16,42,28.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.3,0.0,0.0,0.0
17,43,30.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,51,25.0,2.0,0.0,0.4,4.2,4.2,5.8,0.0,0.0,...,2.1,1.8,0.0,2.6,1.1,0.0,3.2,0.0,0.0,0.8
19,52,49.0,0.0,0.6,0.0,0.0,0.0,1.1,0.0,0.0,...,0.0,0.0,0.0,1.1,1.2,0.0,0.0,0.0,0.0,0.0
20,53,28.4,0.0,0.0,0.0,1.3,0.0,2.0,4.0,0.0,...,4.3,0.0,0.0,0.0,0.0,0.2,1.0,0.0,2.6,8.5
21,54,30.0,0.0,0.9,0.7,0.0,0.0,3.2,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.1,0.9,0.0,1.3,0.0
22,55,140.0,0.0,0.9,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.1,0.0,0.0,0.0,0.0
23,56,176.0,0.0,3.0,0.0,0.0,1.2,0.0,0.9,0.0,...,0.0,0.0,2.2,0.0,0.0,2.4,0.0,0.0,0.0,0.0
24,57,55.0,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5
25,58,198.0,1.3,2.4,1.9,0.0,0.0,0.0,0.0,1.4,...,0.0,2.1,0.0,0.6,0.0,0.0,0.0,0.4,1.9,0.9
26,59,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,61,236.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,...,0.0,0.0,0.5,1.1,0.1,0.3,0.0,0.0,0.0,0.7
28,62,28.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,63,182.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,64,249.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31,71,369.0,0.0,0.0,0.0,0.0,0.0,0.1,0.2,0.0,...,0.7,0.1,0.0,0.0,0.1,0.0,0.0,0.9,0.0,0.0
32,72,38.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.8,0.0,0.0,1.8
33,73,72.0,3.5,0.0,0.0,0.0,0.0,0.0,0.4,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4
34,74,123.0,0.0,0.0,0.0,1.0,0.0,0.2,0.4,0.0,...,0.1,0.0,0.1,0.0,0.0,0.0,0.7,0.0,1.1,1.6
35,75,120.0,0.0,0.0,0.3,1.5,0.0,0.5,0.2,0.0,...,0.7,0.3,2.0,0.1,0.0,1.3,1.0,0.0,0.0,0.6
36,77,250.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37,78,233.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.7,0.0,0.0,0.0
38,81,14.2,0.2,0.0,0.0,0.0,1.0,3.6,0.0,0.0,...,0.0,0.3,0.0,0.0,0.7,0.0,0.0,0.0,0.0,0.0
39,82,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40,83,14.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.2,0.0,0.0,5.2,0.0,0.0,2.1
41,91,200.0,0.2,0.0,0.2,0.0,0.0,0.1,0.0,0.0,...,0.5,0.0,0.3,0.0,0.1,0.0,0.0,0.0,0.0,0.0
42,92,240.0,3.1,3.7,2.6,5.9,0.0,6.0,0.3,3.9,...,3.5,2.6,3.6,1.5,6.8,2.7,3.8,0.6,1.4,1.9
43,95,166.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [74]:
all_1875.to_csv((r'C:\Users\farzi\OneDrive - Johns Hopkins\Research\Inverse Optimization\Data\Python-codes\Blood Pressure and PreDiabetic Samples\all_1875_df.csv'))
male_1875_df.to_csv((r'C:\Users\farzi\OneDrive - Johns Hopkins\Research\Inverse Optimization\Data\Python-codes\Blood Pressure and PreDiabetic Samples\male_1875_df.csv'))
male_1825_df.to_csv((r'C:\Users\farzi\OneDrive - Johns Hopkins\Research\Inverse Optimization\Data\Python-codes\Blood Pressure and PreDiabetic Samples\male_1825_df.csv'))
male_1825_df.to_csv((r'C:\Users\farzi\OneDrive - Johns Hopkins\Research\Inverse Optimization\Data\Python-codes\Blood Pressure and PreDiabetic Samples\male_1825_df.csv'))
male_2635_df.to_csv((r'C:\Users\farzi\OneDrive - Johns Hopkins\Research\Inverse Optimization\Data\Python-codes\Blood Pressure and PreDiabetic Samples\male_2635_df.csv'))
male_3645_df.to_csv((r'C:\Users\farzi\OneDrive - Johns Hopkins\Research\Inverse Optimization\Data\Python-codes\Blood Pressure and PreDiabetic Samples\male_3645_df.csv'))
male_4655_df.to_csv((r'C:\Users\farzi\OneDrive - Johns Hopkins\Research\Inverse Optimization\Data\Python-codes\Blood Pressure and PreDiabetic Samples\male_4655_df.csv'))
male_5665_df.to_csv((r'C:\Users\farzi\OneDrive - Johns Hopkins\Research\Inverse Optimization\Data\Python-codes\Blood Pressure and PreDiabetic Samples\male_5665_df.csv'))
female_1875_df.to_csv((r'C:\Users\farzi\OneDrive - Johns Hopkins\Research\Inverse Optimization\Data\Python-codes\Blood Pressure and PreDiabetic Samples\female_1875_df.csv'))
female_1825_df.to_csv((r'C:\Users\farzi\OneDrive - Johns Hopkins\Research\Inverse Optimization\Data\Python-codes\Blood Pressure and PreDiabetic Samples\female_1825_df.csv'))
female_2635_df.to_csv((r'C:\Users\farzi\OneDrive - Johns Hopkins\Research\Inverse Optimization\Data\Python-codes\Blood Pressure and PreDiabetic Samples\female_2635_df.csv'))
female_3645_df.to_csv((r'C:\Users\farzi\OneDrive - Johns Hopkins\Research\Inverse Optimization\Data\Python-codes\Blood Pressure and PreDiabetic Samples\female_3645_df.csv'))
female_4655_df.to_csv((r'C:\Users\farzi\OneDrive - Johns Hopkins\Research\Inverse Optimization\Data\Python-codes\Blood Pressure and PreDiabetic Samples\female_4655_df.csv'))
female_5665_df.to_csv((r'C:\Users\farzi\OneDrive - Johns Hopkins\Research\Inverse Optimization\Data\Python-codes\Blood Pressure and PreDiabetic Samples\female_5665_df.csv'))